coverage:
  ignore:
  - "test/.*"
  - "tutorial/.*"
  - "src/detail/vsop2013/.*"
  - "src/detail/elp2000/.*"
  - "include/heyoka/detail/tanuki*"
  - "include/heyoka/detail/mdspan*"
  - "src/detail/erfa/.*"

comment: off
