# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  ubuntu_arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_ubuntu_arm64.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
    - ubuntu_arm64
