name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  osx_10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_osx.sh
  windows_2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: conda-forge
          channel-priority: strict
      - name: Build
        shell: pwsh
        run: |
          conda config --set always_yes yes
          conda create --name heyoka cmake llvmdev tbb-devel tbb boost-cpp xtensor xtensor-blas blas blas-devel 'fmt=8.0.*' 'spdlog=1.9.2' sleef
          conda activate heyoka
          mkdir build
          cd build
          cmake ../ -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=%CONDA_PREFIX_PATH% -DHEYOKA_BUILD_TESTS=yes -DHEYOKA_BUILD_TUTORIALS=ON -DHEYOKA_ENABLE_IPO=yes -DBoost_NO_BOOST_CMAKE=ON -DHEYOKA_WITH_SLEEF=yes
          cmake --build . --config Release
          copy Release\heyoka.dll test\Release\
          ctest -j4 -V -C Release
  conda_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_conda_release.sh
  conda_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_conda_coverage.sh
  conda_llvm13_asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_llvm13_conda_asan.sh
  conda_llvm12_asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_llvm12_conda_asan.sh
  conda_llvm11_asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_llvm11_conda_asan.sh
  conda_llvm10_asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash tools/gha_llvm10_conda_asan.sh
